### ISSUE TITLE
Add sound effect when hovering to a new button

### ISSUE THREAD

**Issue by tomtsagk** [tomtsagk/rue#14]
A sound effect is needed when the mouse hovers over a new button. The sound should be short, and possibly a bit simple.

It's possible to hover over multiple buttons very quickly, so if the sound is played multiple times it should be clear how many times it was repeated (one of the reasons why it needs to be short).

Buttons will also generate this sound when navigating the UI with a keyboard.

**Comment by irishdragon47** [comment]
Sample sfx created named "hover-sfx.wav." Made from a 3x oscillator, set all three channels to noise. Delay set to 5%, attack to 8%, hold to 12%, decay to 13%, sustain to 0%, and release to 17%. This makes a "whoosh" sound. It's filtered through Fruity parametric EQ 2's radio preset and EQUO set to flatten the low audible range. File attached.
[hover-sfx.zip](https://github.com/tomtsagk/rue/files/8447472/hover-sfx.zip)

**Comment by tomtsagk** [comment]
This is awesome! I tried it in the game and it really goes well with the buttons animating as they are hovered. Will close this ticket once I finish with the implementation.

**Comment by tomtsagk** [comment]
Added hover sound on buttons and merged in the game
