### ISSUE TITLE
Add sound effect when pressing a button

### ISSUE THREAD

**Issue by tomtsagk** [tomtsagk/rue#15]
When a button is selected (by hovering the mouse over it) it becomes yellow:

![scr1-f](https://user-images.githubusercontent.com/68406639/162271668-ba409b16-1271-414b-9fd8-e255ed52510e.png)

When the user clicks the mouse, it becomes purple and becomes bigger in size:

![scr2-f](https://user-images.githubusercontent.com/68406639/162271865-2e90a08c-0023-4ada-a011-f9b11f09d7e5.png)

I think it would be best to have two different sound effects, one for buttons that do big actions (for example moving from one screen to another), and a different sound effect for buttons that do smaller actions, like changing the volume. Here's an example of the options menu having buttons that do different things:

![scr3-f](https://user-images.githubusercontent.com/68406639/162324565-bb64763d-761f-4bb9-b428-6857e1a5d598.png)

## Big actions

* This is not meant to happen often. When the user does a big action, it will possibly involve the menu animating for the next few seconds, so this sound effect can be a bit larger than the hover sound one (from #14).

## Small actions

* This is meant to happen often, similar to the hover sound effect (#14). One example is the user continuously clicking a button to reduce the game volume.

---

The goal is that, if someone has their eyes closed, they should be able to differentiate between hovering over buttons (hover SFX), moving to other menus (Big Action SFX) or just changing the settings (Small Action SFX).

**Comment by irishdragon47** [comment]
Created files "clickSmall-sfx.wav" and "clickBig-sfx.wav." Small uses a 707 kick drum sample with the radio filter and EQUO, same as the hover sfx and same as the clickBig sfx. Big uses a 707 snare sample with the same effects. File attached.
[clickBig-sfx.zip](https://github.com/tomtsagk/rue/files/8447499/clickBig-sfx.zip)

**Comment by tomtsagk** [comment]
Thanks @irishdragon47 !

Both the big and small sounds are good. I was wondering, could we maybe make the big sound a bit richer? It will mostly be played when moving between menus, which takes a couple of seconds to finish, and I think it would be better if the two sounds were a bit more distinct. Maybe a sound that is a second or two long?

Let me know what you think. If that is too much extra work, happy to keep the one you provided above.

**Comment by irishdragon47** [comment]
It's on my to-do list for the week. This one is very do-able 👍

**Comment by irishdragon47** [comment]
Here's what I think you're asking for. Let me know if this works.
[clickBig-sfx AND Small.zip](https://github.com/tomtsagk/rue/files/8490916/clickBig-sfx.AND.Small.zip)
I went ahead and did the same to the "small" button click too just in case you're interested.

**Comment by tomtsagk** [comment]
Thanks @irishdragon47 , I added those effects on the buttons of all the menus in the game. If needed we can have a look on the next build of the game, for any amends.
