### ISSUE TITLE
Add sound effect when placing a card on the table

### ISSUE THREAD

**Issue by tomtsagk** [tomtsagk/rue#16]
## Journey

When a player looks at the cards in their hand, the card they are looking at becomes a bit larger:

![scr1-f](https://user-images.githubusercontent.com/68406639/162327177-4ace7f20-2a6c-4f49-9fb5-6ece12693d3f.png)

When the player clicks on it once, the card becomes a bit larger, and asks player to click the card again to confirm their choice:

![scr2-f](https://user-images.githubusercontent.com/68406639/162327295-939810db-1814-4d4b-bca7-5b3ab72f84f6.png)

When the card is clicked again, it goes from the players hand to the table:

![scr3-f](https://user-images.githubusercontent.com/68406639/162327434-d8424576-ad4e-43d1-a5fe-e8344c1a1a6e.png)

## Sound effect

Given the above journey, we need a sound effect that will be played as follows:

* It will play when a card is picked and is about to go from someone's hand to the table (both for the player and the AI).
* Maybe the sound effect can emulate the sound of a card being placed on a flat surface?
* This doesn't happen too frequently, so the sound effect could be maximum a few seconds.

**Comment by irishdragon47** [comment]
Tried recording with my setup and I may have to look at getting help or synthesizing something that sounds close.

**Comment by irishdragon47** [comment]
This was a combination of the "handLook-sfx" and "clickSmall-sfx" but with the small click shifted to the right a bit. What do you think of it?
[placeCard-sfx.zip](https://github.com/tomtsagk/rue/files/8507214/placeCard-sfx.zip)

**Comment by tomtsagk** [comment]
Thanks @irishdragon47 !
I've added this into the game now. I think we might need to revisit the volume of each audio, as I think some sound effects might be a bit quiet compared to the background theme.

This is something we can do after the next build is made, and all the audio is in, so we can have a better idea of what adjustments are needed.
