### ISSUE TITLE
Add sound effect when looking at each card

### ISSUE THREAD

**Issue by tomtsagk** [tomtsagk/rue#18]
## Journey

The user can look at each individual card in their hand. By looking at a card, it becomes larger and it's description is shown on the screen. This can be used to view cards before playing one of them:

![scr1-f](https://user-images.githubusercontent.com/68406639/162331089-531ac455-61ea-44d2-a39d-ccb1a4c3978d.png)

## Sound effect

The sound effect needs to satisfy the following:

* It's a very small sound, as the user can very quickly view all cards in their hand, and the sound can be played multiple times quite often.
* Maybe we can use the same sound effect as #14?

**Comment by irishdragon47** [comment]
[handLook-sfx.zip](https://github.com/tomtsagk/rue/files/8490980/handLook-sfx.zip)

**Comment by tomtsagk** [comment]
Awesome sound effect, thanks @irishdragon47 !

I've merged this into the game.
