### ISSUE TITLE
Add sound when selecting a card in your hand

### ISSUE THREAD

**Issue by tomtsagk** [tomtsagk/rue#19]
## Journey

The user can look at cards in their hand. When viewing a card, it becomes slightly larger and its description appears on the screen:

![scr1-f](https://user-images.githubusercontent.com/68406639/162331733-26037b4a-4b3b-4bde-98f2-b0411825f96a.png)

The user can then click the mouse button to select the card, the game would then ask the user to confirm:

![scr2-f](https://user-images.githubusercontent.com/68406639/162331814-767d33f9-4a15-4685-a74e-dbb7f795cd3d.png)

If the user clicks the mouse while looking on the same card, it will be placed on the table. If the user clicks the mouse while looking anywhere else, the card is then de-selected, and the user has to select a card again.

## Sound effect

Two sound effects are needed. One when a card is selected and the user is asked to confirm their choice. Another one is needed when the user clicks away from the card they were asked to confirm, and the card is de-selected.

* Each sound effect should be 1-2 seconds long maximum, but can be smaller.
* The two sounds need to be somewhat related to each other, so it's clear they are connected when heard. Maybe something like, when a card is selected, the sound plays ascending notes, but when a card is de-selected it plays the same notes in descending order? The de-select action should sound a bit more "negative", given the choice.
* Not sure if it matters, but the sound effects will be played in a ping-pong fashion, as in, you can only hear the de-select sound after hearing the select sound. You can never hear two select sounds in a row (a card needs to be de-selected before a new one is selected).

**Comment by irishdragon47** [comment]
Created "cardChoose-sfx.wav," "cardSelect-sfx.wav," and "cardDeselect.wav." Choose and Select were both on a major C6 note, with Choose being C6 then D6 in rapid ascending order. I tried descending order for Deselect, but found doing a G4# + C5# chord sounded better. I can export descending order if I need to, but if the notes are too close to Choose and Select it may not be distinct enough. Zip of sfx attached.
[cardChoose-sfx.zip](https://github.com/tomtsagk/rue/files/8447454/cardChoose-sfx.zip)

**Comment by tomtsagk** [comment]
Awesome work @irishdragon47 !

The `cardSelect-sfx.wav` and `cardDeselect-sfx.wav` are perfect, will add them in the game in the following days.

For the `cardChoose-sfx.wav`, the description mentions two sound effects. Is that for when a card is chosen and is about to be moved to the table? (#16)

**Comment by irishdragon47** [comment]
Thanks! And no, "choose" might be better named "confirm." I'm waiting until the week starts for me to record all the sounds I can use real cards for.

**Comment by tomtsagk** [comment]
Awesome job @irishdragon47 !

I've merged these into the game.
