### ISSUE TITLE
OST - Main Menu Theme

### ISSUE THREAD

**Issue by irishdragon47** [tomtsagk/rue#2]
Established loops, need guitar track, then need to organize loops, apply automation tracks

**Comment by irishdragon47** [comment]
Added guitar tracks, working through the layout

**Comment by irishdragon47** [comment]
Instruments are tracked, refining sounds/samples

**Comment by irishdragon47** [comment]
Track submitted for review

**Comment by tomtsagk** [comment]
Great work! I added the main menu theme, and it will be part of the game on the next build.
