### ISSUE TITLE
In-game theme

### ISSUE THREAD

**Issue by irishdragon47** [tomtsagk/rue#5]
Main menu is set to 65 BPM. I'll start working soon on having a 90-130 BPM track for matches.

The goal will be to have more notes per measure, slightly harsher sounds, but not be distracting enough to make it hard to read the cards.

May take some inspiration from melodies like Crash Bandicoot 2 end credits theme (as in similar musical scale to the xylophone thing) but still following the previous instructions of metal, but not too heavy.

The synths/pads will be more sawtooth/angular instead of sine for a harsher sound.

I'm considering having a 5-10 second stinger at the start, which may make it non-loopable, meaning I'll have to export the stinger by itself so the game can handle it. Unless there's some other way to manage it in programming, to loop from a timestamp other than 0:00.

**Comment by tomtsagk** [comment]
> I'm considering having a 5-10 second stinger at the start, which may make it non-loopable, meaning I'll have to export the stinger by itself so the game can handle it. Unless there's some other way to manage it in programming, to loop from a timestamp other than 0:00.

That sounds good, but currently it might be a bit of extra effort to make only the first part non-loopable, from a programming point of view.

Do you thing as a first step we can have something that is completely loopable, to the point the user can't tell when the track end or begins, and revisit it in the future?

Alternatively, we can have the whole track, including the stinger at the start, but when the music loops it can do a fade-out fade-in effect.

Let me know what you think :)

**Comment by irishdragon47** [comment]
I'll go with what I was originally going to do two weeks ago (remembering the [KISS ](https://en.wikipedia.org/wiki/KISS_principle) principle), just making it a little harsher and more energetic.

**Comment by irishdragon47** [comment]
In-game theme submitted for review

**Comment by tomtsagk** [comment]
Sounds interesting and playful. Great work! I've added it in, and it will be part of the game in the next build.
